id: D1801DF0E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-08T09:40:23+00:00'
last_modified: '2022-05-30T06:46:44.220831+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    faa0:
      image_group_id: I1PD95882
      title: ''
      total_pages: 1379
      order: 37
      base_file: faa0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
