id: PF7A2F6E7
initial_creation_type: ocr
source_metadata:
  volumes:
    7cfbc228526545238522fdaed3f4e7d3:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ''
      total_pages: 1379
      volume_number: 37
